### ISSUE TITLE
Support for 1.20.4?

### ISSUE THREAD

**Issue by seriousfreezing** [realSmushyTaco/Solar-Apocalypse#3]

**Comment by SmushyTaco** [comment]
I'm skipping 1.20.4 support for all my mods. I'll update all my mods to 1.20.5 when it's released. The current version may work for 1.20.4, but I won't test it or fix it if it doesn't.

**Comment by seriousfreezing** [comment]
Ok ok! Thank you!

**Comment by seriousfreezing** [comment]
I just tested it and it doesn't work even if I change fabric.mod.json
I'll wait for an update to 1.20.5 anyway.
