### ISSUE TITLE
Crashes on day 9

### ISSUE THREAD

**Issue by seriousfreezing** [realSmushyTaco/Solar-Apocalypse#4]
I've just tested the mod myself and it only crashes on day 9. There have been no changes to its configuration or anything like that.
https://paste.atlauncher.com/view/b4ba9c2b-2c63-41b8-a863-cdb29402498d

**Comment by DefomCode** [comment]
The link does not work

**Comment by seriousfreezing** [comment]
https://paste.atlauncher.com/view/372af1db-2d28-4b4f-af3d-afae5a89b861
[crash-2024-07-18_14.58.40-client.txt](https://github.com/user-attachments/files/16287141/crash-2024-07-18_14.58.40-client.txt)
The previous log probably no longer exists because it took them a while to see it.

**Comment by SmushyTaco** [comment]
Fixed
