### ISSUE TITLE
Smooth transition at each stage

### ISSUE THREAD

**Issue by seriousfreezing** [realSmushyTaco/Solar-Apocalypse#6]
.

**Comment by SmushyTaco** [comment]
I'll look into this

**Comment by SmushyTaco** [comment]
I've added smooth transitions for the sun size. Adding smooth transitions for the color changes and cloud removal will be a little trickier so that'll be attempted at a later date. No promises but I'll try.

**Comment by seriousfreezing** [comment]
I think it's already perfect because of the transition in the size of the sun, the rest is profit.

**Comment by SmushyTaco** [comment]
@seriousfreezing sky color, fog color, and sky light transition now too. I'll look into fading out the clouds next but it'll probably be tricky to implement.

**Comment by SmushyTaco** [comment]
@seriousfreezing fading clouds has been implemented. Everything now has smooth transitions! Thank you for the suggestion.

Note: optimization mods might break the cloud fading effect and make it instant, that's out of my reach.

**Comment by seriousfreezing** [comment]
Could you tell me which optimization mods could cause this? For me to remove or do you mean mods that change the behavior of the clouds?

**Comment by SmushyTaco** [comment]
@seriousfreezing I have no idea which one(s) cause this. It's one of the mods in Fabulously Optimized. If you ever figure it out yourself let me know!

**Comment by SmushyTaco** [comment]
@seriousfreezing it was Sodium causing the issue. I've released an update adding Sodium support so all transitions now work perfectly regardless of what optimization mods you may have.
